name: GitHub-Profile-3D-Contrib

on:
  schedule: # 06:00
    - cron: "0 22 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name EriciusX
          git config user.email 1144769490@qq.com
          git add -A .
          git commit -m "generated[Auto]"
          git push
